import Link from 'next/link';
import Shell from '@/components/Shell';
import { Layers3, MessageCircleQuestion, Eye, Route, BookOpenCheck, ListChecks, MessageSquareText, TrendingUp, ShieldCheck, RefreshCcw, UsersRound, PencilRuler, Compass, ArrowRight, Check } from 'lucide-react';

export default function AboutPage(){
  return <Shell>
    <section className="page-hero"><div className="container page-hero-grid"><div><div className="eyebrow">About LOKOAX</div><h1 className="page-title">Learning should feel clear, structured and achievable.</h1><p className="lead">LOKOAX is designed to remove friction from learning and make the next useful step obvious — learn, practice, understand and improve.</p><div className="hero-actions"><Link href="/signup?plan=free" className="button button-primary">Explore subjects</Link><Link href="/#experience" className="button button-secondary">See the learning flow</Link></div></div><div className="page-hero-card card"><h3>A learning loop designed for progress</h3><div className="quick-list">{[['Learn','Clear explanations and structured lessons'],['Practice','Apply concepts while they are fresh'],['Understand','Use feedback to identify gaps'],['Improve','Repeat with confidence and track growth']].map(([title,copy],i)=><div className="quick-item" key={title}><span>{i+1}</span><div><strong>{title}</strong><small>{copy}</small></div></div>)}</div></div></div></section>

    <section className="section"><div className="container"><div className="section-heading"><div><div className="eyebrow">Why we exist</div><h2 className="section-title">Make learning feel less overwhelming.</h2><p>Students often know they need to learn, but not what to do next. LOKOAX is designed to close that gap.</p></div></div><div className="problem-grid">{[['Too much information','Turn scattered material into a clear learning path.',Layers3],['Practice without feedback','Make practice useful with clear context and review.',MessageCircleQuestion],['Progress that feels invisible','Show learners what they have completed and where to focus next.',Eye]].map(([title,copy,Icon])=><article className="info-card card" key={title}><span className="info-icon"><Icon size={20}/></span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

    <section className="section section-soft"><div className="container"><div className="section-heading"><div><div className="eyebrow">Our learning philosophy</div><h2 className="section-title">Designed around how progress actually happens.</h2><p>Good learning experiences reduce cognitive load, encourage active practice and make improvement visible.</p></div></div><div className="philosophy-grid">{[['Clarity before complexity','Explain the idea simply before adding depth.',Route],['Practice while learning','Move quickly from reading or watching into doing.',ListChecks],['Feedback that teaches','Use answers and explanations to reinforce understanding.',MessageSquareText],['Progress that motivates','Help learners see small wins and build momentum.',TrendingUp]].map(([title,copy,Icon])=><article className="info-card card" key={title}><span className="info-icon"><Icon size={20}/></span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

    <section className="section" id="mission"><div className="container"><div className="mission-card"><div><div className="eyebrow" style={{color:'#cfe2ff'}}>Our mission</div><h2 className="section-title">Give every learner a clearer path from confusion to confidence.</h2><p>We want LOKOAX to combine high-quality educational content, meaningful practice and simple progress tools in one experience that students can return to every day.</p></div><div className="mission-values"><span><strong>Structured</strong><br/>Follow an intentional path</span><span><strong>Practical</strong><br/>Learn by applying concepts</span><span><strong>Visible</strong><br/>See progress over time</span></div></div></div></section>

    <section className="section"><div className="container"><div className="section-heading"><div><div className="eyebrow">Content quality</div><h2 className="section-title">Quality is a process, not a badge.</h2><p>Content should be accurate, understandable, curriculum-aware and genuinely useful in practice.</p></div></div><div className="quality-grid">{[['Map the curriculum','Organise subjects into clear topics, chapters and learning outcomes.',BookOpenCheck],['Build for understanding','Write explanations, examples and visuals around the learner’s point of view.',PencilRuler],['Design purposeful practice','Connect questions and quizzes directly to the concepts being learned.',ListChecks],['Review and improve','Use educator review, learner feedback and product data to keep content useful.',RefreshCcw]].map(([title,copy,Icon])=><article className="info-card card" key={title}><span className="info-icon"><Icon size={20}/></span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

    <section className="section section-soft"><div className="container"><div className="section-heading"><div><div className="eyebrow">People behind the learning</div><h2 className="section-title">Built with educators. Shaped by learners.</h2><p>This area is intentionally ready for educator and subject-specialist profiles when the team is finalised.</p></div></div><div className="team-grid">{[['Subject educators','Review accuracy, sequencing and learning outcomes.',UsersRound],['Content specialists','Turn difficult concepts into clear, teachable explanations.',BookOpenCheck],['Learning & product design','Shape practice, feedback and progress experiences around real learner needs.',PencilRuler]].map(([title,copy,Icon])=><article className="info-card card" key={title}><span className="info-icon"><Icon size={20}/></span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

    <section className="section"><div className="container"><div className="section-heading"><div><div className="eyebrow">Our vision</div><h2 className="section-title">A learning platform that grows with the learner.</h2><p>Learning should feel connected across subjects, practice, progress and confidence instead of living in separate tools.</p></div></div><div className="vision-grid">{[['Today','Structured lessons, practice, quizzes and progress tracking in one place.',ShieldCheck],['Next','More guided pathways, richer progress insight and deeper subject coverage.',Compass],['Future','A platform that helps every learner understand what to learn next — and why.',TrendingUp]].map(([title,copy,Icon])=><article className="info-card card" key={title}><span className="info-icon"><Icon size={20}/></span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

    <section className="cta-section"><div className="container"><div className="cta-banner"><div><h2>Ready to see LOKOAX in action?</h2><p>Explore a subject, try a lesson and experience the learning flow for yourself.</p><Link className="button button-primary" href="/signup?plan=free">Start Learning Free <ArrowRight size={16}/></Link></div><div></div><div className="cta-list"><strong>Learn → Practice → Improve</strong>{['Structured lessons','Purposeful practice','Visible progress'].map(item=><span key={item}><Check size={15}/>{item}</span>)}</div></div></div></section>
  </Shell>
}
